/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AshiyaMichi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Michi
 */
public class DashMenu extends javax.swing.JFrame {

    /**
     * Creates new form DashMenu
     */
    public DashMenu() {
        initComponents();
        Date();
        Time();
    }
    public void ItemCost() {
        double sum = 0;
        for (int i = 0; i < varTable.getRowCount(); i++) {
            sum = sum + Double.parseDouble(varTable.getValueAt(i, 2).toString());
        }
        varSubTotal.setText(Double.toString(sum));
        double Total = Double.parseDouble(varSubTotal.getText());

        double Tax = (Total * 3.9) / 100;
        String TaxTotal = String.format("PHP %.2f", Tax);
        varTax.setText(TaxTotal);

        String SubTotal = String.format("PHP %.2f", Total);
        varSubTotal.setText(SubTotal);

        String Total1 = String.format("PHP %.2f", Total + Tax);
        varTotal.setText(Total1);
    }
    public void Change() {
        double sum = 0;
        double cash = Double.parseDouble(varCash.getText());

        for (int i = 0; i < varTable.getRowCount(); i++) {
            sum = sum + Double.parseDouble(varTable.getValueAt(i, 2).toString());
        }

        double Tax = (sum * 3.9) / 100;
        double change = (cash - (sum + Tax));

        String ChangeGiven = String.format("PHP %.2f", change);
        varChange.setText(ChangeGiven);
    }
    public void Date() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String Date = dateFormat.format(date);
        varDate.setText(Date);

    }

    public void Time() {
         new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");

                varTime.setText(dateFormat.format(date));
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        varCate1 = new javax.swing.JButton();
        varCate2 = new javax.swing.JButton();
        varCate3 = new javax.swing.JButton();
        varLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        varDate = new javax.swing.JLabel();
        varTime = new javax.swing.JLabel();
        varTab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        varItem1 = new javax.swing.JLabel();
        varItem2 = new javax.swing.JLabel();
        varItem3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        varItem4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        varItem9 = new javax.swing.JLabel();
        varItem10 = new javax.swing.JLabel();
        varItem11 = new javax.swing.JLabel();
        varItem12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        varItem5 = new javax.swing.JLabel();
        varItem6 = new javax.swing.JLabel();
        varItem7 = new javax.swing.JLabel();
        varItem8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        varTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        varCash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        varChange = new javax.swing.JTextField();
        varBuy = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        varPurchase = new javax.swing.JButton();
        varRemoveItem = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        varPurchase1 = new javax.swing.JButton();
        varPurchase2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        varSubTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        varTax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        varTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashMenu");
        setPreferredSize(new java.awt.Dimension(1024, 668));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/AshiyaMichi Foodie.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varCate1.setBackground(new java.awt.Color(153, 153, 153));
        varCate1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        varCate1.setText("Niku no kategorī ");
        varCate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varCate1MouseClicked(evt);
            }
        });
        varCate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCate1ActionPerformed(evt);
            }
        });
        jPanel3.add(varCate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 80));

        varCate2.setBackground(new java.awt.Color(153, 153, 153));
        varCate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        varCate2.setText("Dezāto Kategorī ");
        varCate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCate2ActionPerformed(evt);
            }
        });
        jPanel3.add(varCate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 80));

        varCate3.setBackground(new java.awt.Color(153, 153, 153));
        varCate3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        varCate3.setText("Dorinkukategorī");
        varCate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCate3ActionPerformed(evt);
            }
        });
        jPanel3.add(varCate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 80));

        varLogOut.setBackground(new java.awt.Color(153, 153, 153));
        varLogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        varLogOut.setText("LOGOUT");
        varLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varLogOutActionPerformed(evt);
            }
        });
        jPanel3.add(varLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/BackIcon.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 129, 248, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        varDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varDate.setText("Date");

        varTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varTime.setText("Time");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(varDate)
                .addGap(63, 63, 63)
                .addComponent(varTime)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(varDate)
                .addComponent(varTime))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 230, -1));

        varTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/1.png"))); // NOI18N
        varItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem1MouseClicked(evt);
            }
        });
        jPanel5.add(varItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 65, -1, -1));

        varItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/Item1.png"))); // NOI18N
        varItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem2MouseClicked(evt);
            }
        });
        jPanel5.add(varItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 272, -1, -1));

        varItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/2.png"))); // NOI18N
        varItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem3MouseClicked(evt);
            }
        });
        jPanel5.add(varItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 65, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Niku no kategorī ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 17, -1, -1));

        varItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/item4.png"))); // NOI18N
        varItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem4MouseClicked(evt);
            }
        });
        jPanel5.add(varItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 272, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/TabIcon.gif"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 510));

        varTab.addTab("tab1", jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/5.png"))); // NOI18N
        varItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem9MouseClicked(evt);
            }
        });
        jPanel7.add(varItem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 74, 160, 200));

        varItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/6.png"))); // NOI18N
        varItem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem10MouseClicked(evt);
            }
        });
        jPanel7.add(varItem10, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 74, 160, 200));

        varItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/7.png"))); // NOI18N
        varItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem11MouseClicked(evt);
            }
        });
        jPanel7.add(varItem11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 280, 160, 200));

        varItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/8.png"))); // NOI18N
        varItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem12MouseClicked(evt);
            }
        });
        jPanel7.add(varItem12, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 280, 160, 200));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Dezāto Kategorī ");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 22, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/TabIcon.gif"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 510));

        varTab.addTab("tab3", jPanel7);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/9.png"))); // NOI18N
        varItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem5MouseClicked(evt);
            }
        });
        jPanel6.add(varItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 63, 160, 200));

        varItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/11.png"))); // NOI18N
        varItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem6MouseClicked(evt);
            }
        });
        jPanel6.add(varItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 298, 160, 200));

        varItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/12.png"))); // NOI18N
        varItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem7MouseClicked(evt);
            }
        });
        jPanel6.add(varItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 298, 160, 200));

        varItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/10.png"))); // NOI18N
        varItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varItem8MouseClicked(evt);
            }
        });
        jPanel6.add(varItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 63, 160, 200));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Dorinkukategorī");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 23, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AshiyaMichi/Image/TabIcon.gif"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 510));

        varTab.addTab("tab2", jPanel6);

        jPanel1.add(varTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 550));

        varTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(varTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 290, 130));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cash:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Change:");

        varBuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Payment Method:");

        varPurchase.setBackground(new java.awt.Color(102, 204, 255));
        varPurchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varPurchase.setText("Purchase");
        varPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPurchaseActionPerformed(evt);
            }
        });

        varRemoveItem.setBackground(new java.awt.Color(102, 204, 255));
        varRemoveItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varRemoveItem.setText("Remove Item");
        varRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varCash, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(varChange))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(varPurchase)
                            .addGap(33, 33, 33)
                            .addComponent(varRemoveItem))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(varCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(varChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varRemoveItem)
                    .addComponent(varPurchase))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 280, 160));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        varPurchase1.setBackground(new java.awt.Color(102, 204, 255));
        varPurchase1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varPurchase1.setText("Reset Items");
        varPurchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPurchase1ActionPerformed(evt);
            }
        });

        varPurchase2.setBackground(new java.awt.Color(102, 204, 255));
        varPurchase2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varPurchase2.setText("Print Info");
        varPurchase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPurchase2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sub Total:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tax:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varTax, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(varSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(varPurchase1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(varPurchase2)
                        .addGap(58, 58, 58))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(varSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(varTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varPurchase1)
                    .addComponent(varPurchase2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 300, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varCate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCate1ActionPerformed
        // TODO add your handling code here:
        varTab.setSelectedIndex(0);
    }//GEN-LAST:event_varCate1ActionPerformed

    private void varCate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varCate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_varCate1MouseClicked

    private void varCate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCate2ActionPerformed
        // TODO add your handling code here:
        varTab.setSelectedIndex(1);
    }//GEN-LAST:event_varCate2ActionPerformed

    private void varCate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCate3ActionPerformed
        // TODO add your handling code here:
        varTab.setSelectedIndex(2);
    }//GEN-LAST:event_varCate3ActionPerformed

    private void varLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varLogOutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure to LogOut?","LOGOUT",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_NO_OPTION) {
            Login login = new Login();
            login.show();
            this.dispose();
        } else {
            
        }
    }//GEN-LAST:event_varLogOutActionPerformed

    private void varPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPurchase1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        JOptionPane.showMessageDialog(null,"Successfully Reset Items","Reset",JOptionPane.PLAIN_MESSAGE);
        model.setRowCount(0);
        varChange.setText("");
        varTax.setText("");
        varTotal.setText("");
        varSubTotal.setText("");
        varCash.setText("");
    }//GEN-LAST:event_varPurchase1ActionPerformed

    private void varItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem5MouseClicked
        // TODO add your handling code here:
        double PriceItem = 140.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Ice Cream Sundae", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem5MouseClicked

    private void varItem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem8MouseClicked
        // TODO add your handling code here:
        double PriceItem = 200.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Chocolate Town Special", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem8MouseClicked

    private void varItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem6MouseClicked
        // TODO add your handling code here:
        double PriceItem = 149.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Ice Cream Oreo", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem6MouseClicked

    private void varItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem7MouseClicked
        // TODO add your handling code here:
        double PriceItem = 149.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Chocolate Lasagna", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem7MouseClicked

    private void varItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem9MouseClicked
        // TODO add your handling code here:
        double PriceItem = 66.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Oreo Shake", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem9MouseClicked

    private void varItem10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem10MouseClicked
        // TODO add your handling code here:
        double PriceItem = 129.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Cold Choco", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem10MouseClicked

    private void varItem11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem11MouseClicked
        // TODO add your handling code here:
        double PriceItem = 88.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Froasted Coffee Float", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem11MouseClicked

    private void varItem12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_varItem12MouseClicked

    private void varItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem1MouseClicked
        // TODO add your handling code here:
        double PriceItem = 59.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Tonkatsu", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem1MouseClicked

    private void varItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem3MouseClicked
        // TODO add your handling code here:
        double PriceItem = 189.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Pork Katsu", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem3MouseClicked

    private void varItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem2MouseClicked
        // TODO add your handling code here:
        double PriceItem = 178.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Chicken Karaage", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem2MouseClicked

    private void varItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varItem4MouseClicked
        // TODO add your handling code here:
        double PriceItem = 228.0;
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        model.addRow(new Object[]{"Chashu(Pork Belly)", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_varItem4MouseClicked

    private void varPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPurchaseActionPerformed
        // TODO add your handling code here:
        if (varBuy.getSelectedItem().equals("Cash")) {
            JOptionPane.showMessageDialog(null, "Successfully Purchase the Item!","Success",JOptionPane.PLAIN_MESSAGE);
            Change();
        } else {
            varChange.setText("");
            varCash.setText("");
        }
    }//GEN-LAST:event_varPurchaseActionPerformed

    private void varRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varRemoveItemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) varTable.getModel();
        int RemoveItem = varTable.getSelectedRow();
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
            JOptionPane.showMessageDialog(null,"Successfully Remove Item","Remove",JOptionPane.PLAIN_MESSAGE);
        }
        ItemCost();
        if (varBuy.getSelectedItem().equals("Cash")) {
            JOptionPane.showMessageDialog(null, "You remove the item","Remove",JOptionPane.PLAIN_MESSAGE);
        } else {
            varChange.setText("");
            varCash.setText("");
        }
    }//GEN-LAST:event_varRemoveItemActionPerformed

    private void varPurchase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPurchase2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Info");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            varTable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_varPurchase2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> varBuy;
    private javax.swing.JTextField varCash;
    private javax.swing.JButton varCate1;
    private javax.swing.JButton varCate2;
    private javax.swing.JButton varCate3;
    private javax.swing.JTextField varChange;
    private javax.swing.JLabel varDate;
    private javax.swing.JLabel varItem1;
    private javax.swing.JLabel varItem10;
    private javax.swing.JLabel varItem11;
    private javax.swing.JLabel varItem12;
    private javax.swing.JLabel varItem2;
    private javax.swing.JLabel varItem3;
    private javax.swing.JLabel varItem4;
    private javax.swing.JLabel varItem5;
    private javax.swing.JLabel varItem6;
    private javax.swing.JLabel varItem7;
    private javax.swing.JLabel varItem8;
    private javax.swing.JLabel varItem9;
    private javax.swing.JButton varLogOut;
    private javax.swing.JButton varPurchase;
    private javax.swing.JButton varPurchase1;
    private javax.swing.JButton varPurchase2;
    private javax.swing.JButton varRemoveItem;
    private javax.swing.JTextField varSubTotal;
    private javax.swing.JTabbedPane varTab;
    private javax.swing.JTable varTable;
    private javax.swing.JTextField varTax;
    private javax.swing.JLabel varTime;
    private javax.swing.JTextField varTotal;
    // End of variables declaration//GEN-END:variables
}
