/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Date();
        Time();
    }

    // for functions 
    public void ItemCost() {
        double sum = 0;
        for (int i = 0; i < itemTable.getRowCount(); i++) {
            sum = sum + Double.parseDouble(itemTable.getValueAt(i, 2).toString());
        }
        varSubtotal.setText(Double.toString(sum));
        double Total = Double.parseDouble(varSubtotal.getText());

        double Tax = (Total * 3.9) / 100;
        String TaxTotal = String.format("PHP %.2f", Tax);
        varTax.setText(TaxTotal);

        String SubTotal = String.format("PHP %.2f", Total);
        varSubtotal.setText(SubTotal);

        String Total1 = String.format("PHP %.2f", Total + Tax);
        varTotal.setText(Total1);
    }

    public void Change() {
        double sum = 0;
        double cash = Double.parseDouble(varDisplay.getText());

        for (int i = 0; i < itemTable.getRowCount(); i++) {
            sum = sum + Double.parseDouble(itemTable.getValueAt(i, 2).toString());
        }

        double Tax = (sum * 3.9) / 100;
        double change = (cash - (sum + Tax));

        String ChangeGiven = String.format("PHP %.2f", change);
        varChange.setText(ChangeGiven);
    }

    public void Date() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String Date = dateFormat.format(date);
        varDate.setText(Date);

    }

    public void Time() {
         new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");

                varTime.setText(dateFormat.format(date));
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        varBtn7 = new javax.swing.JButton();
        varBtn8 = new javax.swing.JButton();
        varBtn9 = new javax.swing.JButton();
        varBtn4 = new javax.swing.JButton();
        varBtn5 = new javax.swing.JButton();
        varBtn6 = new javax.swing.JButton();
        varBtn1 = new javax.swing.JButton();
        varBtn2 = new javax.swing.JButton();
        varBtn3 = new javax.swing.JButton();
        varBtn0 = new javax.swing.JButton();
        varBtnDot = new javax.swing.JButton();
        varBtnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        item1 = new javax.swing.JButton();
        item2 = new javax.swing.JButton();
        item3 = new javax.swing.JButton();
        item4 = new javax.swing.JButton();
        item5 = new javax.swing.JButton();
        item6 = new javax.swing.JButton();
        item7 = new javax.swing.JButton();
        item8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        varSubtotal = new javax.swing.JTextField();
        varTax = new javax.swing.JTextField();
        varTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        varDisplay = new javax.swing.JTextField();
        varChange = new javax.swing.JTextField();
        varPayMethod = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        varPay = new javax.swing.JButton();
        varPrint = new javax.swing.JButton();
        varReset = new javax.swing.JButton();
        varRemove = new javax.swing.JButton();
        varExit = new javax.swing.JButton();
        varPriceList = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        varTime = new javax.swing.JLabel();
        varDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FoodMenu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        varBtn7.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn7.setText("7");
        varBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn7ActionPerformed(evt);
            }
        });

        varBtn8.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn8.setText("8");
        varBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn8ActionPerformed(evt);
            }
        });

        varBtn9.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn9.setText("9");
        varBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn9ActionPerformed(evt);
            }
        });

        varBtn4.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn4.setText("4");
        varBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn4ActionPerformed(evt);
            }
        });

        varBtn5.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn5.setText("5");
        varBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn5ActionPerformed(evt);
            }
        });

        varBtn6.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn6.setText("6");
        varBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn6ActionPerformed(evt);
            }
        });

        varBtn1.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn1.setText("1");
        varBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn1ActionPerformed(evt);
            }
        });

        varBtn2.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn2.setText("2");
        varBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn2ActionPerformed(evt);
            }
        });

        varBtn3.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn3.setText("3");
        varBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn3ActionPerformed(evt);
            }
        });

        varBtn0.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtn0.setText("0");
        varBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtn0ActionPerformed(evt);
            }
        });

        varBtnDot.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtnDot.setText(".");
        varBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtnDotActionPerformed(evt);
            }
        });

        varBtnClear.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        varBtnClear.setText("C");
        varBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(varBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(varBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(varBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(varBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(varBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(varBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(varBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(varBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(varBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(varBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varBtn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(varBtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        item1.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/blackForestChocolate.png"))); // NOI18N
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });

        item2.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/caramelcake.png"))); // NOI18N
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });

        item3.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/brownieBottomed.png"))); // NOI18N
        item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3ActionPerformed(evt);
            }
        });

        item4.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/chocolate lasagna.png"))); // NOI18N
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });

        item5.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/oreoshake.png"))); // NOI18N
        item5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5ActionPerformed(evt);
            }
        });

        item6.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/strawberryShake.png"))); // NOI18N
        item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6ActionPerformed(evt);
            }
        });

        item7.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/cokefloat.png"))); // NOI18N
        item7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item7ActionPerformed(evt);
            }
        });

        item8.setFont(new java.awt.Font("Script MT Bold", 0, 48)); // NOI18N
        item8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/hotchoco.png"))); // NOI18N
        item8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("SubTotal:");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel2.setText("Tax:");

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel3.setText("Total:");

        varSubtotal.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N

        varTax.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N

        varTotal.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varTax, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(varSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(varSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(varTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel4.setText("Payment Method:");

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Cash:");

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel6.setText("Change");

        varDisplay.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N

        varChange.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N

        varPayMethod.setEditable(true);
        varPayMethod.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        varPayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Maya", "Gcash" }));
        varPayMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPayMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(varDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addComponent(varChange))
                    .addComponent(varPayMethod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(varPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(varDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(varChange, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        varPay.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varPay.setForeground(new java.awt.Color(255, 102, 102));
        varPay.setText("Pay");
        varPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPayActionPerformed(evt);
            }
        });

        varPrint.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varPrint.setForeground(new java.awt.Color(204, 102, 0));
        varPrint.setText("Print");
        varPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPrintActionPerformed(evt);
            }
        });

        varReset.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varReset.setForeground(new java.awt.Color(0, 204, 102));
        varReset.setText("Reset");
        varReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varResetActionPerformed(evt);
            }
        });

        varRemove.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varRemove.setForeground(new java.awt.Color(0, 102, 102));
        varRemove.setText("Remove");
        varRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varRemoveActionPerformed(evt);
            }
        });

        varExit.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varExit.setForeground(new java.awt.Color(153, 153, 255));
        varExit.setText("LOG OUT");
        varExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varExitActionPerformed(evt);
            }
        });

        varPriceList.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        varPriceList.setForeground(new java.awt.Color(204, 0, 153));
        varPriceList.setText("Price List");
        varPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPriceListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(varExit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varPriceList, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(varPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(varRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varPay)
                    .addComponent(varReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varPrint)
                    .addComponent(varRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varExit)
                    .addComponent(varPriceList))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel7.setPreferredSize(new java.awt.Dimension(622, 133));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hciProject/Images/kanna-dragon-maid.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        varTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varTime.setText("Time");

        varDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varDate.setText("Date");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(varDate)
                .addGap(72, 72, 72)
                .addComponent(varTime)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varDate)
                    .addComponent(varTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public void setString(String string) {
        this.string = string;
    }

    private void varPayMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPayMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varPayMethodActionPerformed

    private void varBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn7ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn7.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn7.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn7ActionPerformed

    private void varBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn8ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn8.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn8.getText();
            varDisplay.setText(enNumber);
        }

    }//GEN-LAST:event_varBtn8ActionPerformed

    private void varBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn9ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn9.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn9.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn9ActionPerformed

    private void varBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn4ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn4.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn4.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn4ActionPerformed

    private void varBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn5ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn5.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn5.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn5ActionPerformed

    private void varBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn6ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn6.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn6.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn6ActionPerformed

    private void varBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn1ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn1.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn1.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn1ActionPerformed

    private void varBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn2ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn2.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn2.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn2ActionPerformed

    private void varBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn0ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn0.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn0.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn0ActionPerformed

    private void varBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtnDotActionPerformed
        // TODO add your handling code here:
        if (!varDisplay.getText().contains(".")) {
            varDisplay.setText(varDisplay.getText() + varBtnDot.getText());
        }
    }//GEN-LAST:event_varBtnDotActionPerformed

    private void varBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtnClearActionPerformed
        // TODO add your handling code here:
        varDisplay.setText("");
        varChange.setText("");
    }//GEN-LAST:event_varBtnClearActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 350.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"BlackForestCake", "1", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item1ActionPerformed

    private void varPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPayActionPerformed
        // TODO add your handling code here:
        if (varPayMethod.getSelectedItem().equals("Cash")) {
            JOptionPane.showMessageDialog(null, "Successfully Purchase the Item!","Success",JOptionPane.PLAIN_MESSAGE);
            Change();
        } else {
            varChange.setText("");
            varDisplay.setText("");
        }
    }//GEN-LAST:event_varPayActionPerformed

    private void varResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.setRowCount(0);
        varChange.setText("");
        varTax.setText("");
        varTotal.setText("");
        varSubtotal.setText("");
        varDisplay.setText("");
    }//GEN-LAST:event_varResetActionPerformed

    private void varPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printing in Progress...");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            itemTable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_varPrintActionPerformed

    private void varRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        int RemoveItem = itemTable.getSelectedRow();
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        if (varPayMethod.getSelectedItem().equals("Cash")) {
            JOptionPane.showMessageDialog(null, "You remove the item","Remove",JOptionPane.PLAIN_MESSAGE);
        } else {
            varChange.setText("");
            varDisplay.setText("");
        }
    }//GEN-LAST:event_varRemoveActionPerformed

    private void varExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varExitActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Are you sure to LogOut?", "LogOut", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.show();
            this.dispose();
        } else {
            //nothing here
        }
    }//GEN-LAST:event_varExitActionPerformed

    private void varBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varBtn3ActionPerformed
        // TODO add your handling code here:
        String enNumber = varDisplay.getText();

        if (enNumber == "") {
            varDisplay.setText(varBtn3.getText());

        } else {
            enNumber = varDisplay.getText() + varBtn3.getText();
            varDisplay.setText(enNumber);
        }
    }//GEN-LAST:event_varBtn3ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 390.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"CaramelCake", "2", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item2ActionPerformed

    private void item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 295.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"Brownie bottomed", "3", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item3ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 500.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"Chocolate lasanga", "4", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item4ActionPerformed

    private void item5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 150.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"OreoShake", "5", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item5ActionPerformed

    private void item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 129.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"Strawberry Shake", "6", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item6ActionPerformed

    private void item7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item7ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 99.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"Coke Float", "7", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item7ActionPerformed

    private void item8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item8ActionPerformed
        // TODO add your handling code here:
        double PriceItem = 77.0;
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.addRow(new Object[]{"Hot Choco", "8", PriceItem});
        ItemCost();
    }//GEN-LAST:event_item8ActionPerformed

    private void varPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPriceListActionPerformed
        // TODO add your handling code here:
        PriceList pricelist = new PriceList();
        pricelist.show();
    }//GEN-LAST:event_varPriceListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JButton item1;
    private javax.swing.JButton item2;
    private javax.swing.JButton item3;
    private javax.swing.JButton item4;
    private javax.swing.JButton item5;
    private javax.swing.JButton item6;
    private javax.swing.JButton item7;
    private javax.swing.JButton item8;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton varBtn0;
    private javax.swing.JButton varBtn1;
    private javax.swing.JButton varBtn2;
    private javax.swing.JButton varBtn3;
    private javax.swing.JButton varBtn4;
    private javax.swing.JButton varBtn5;
    private javax.swing.JButton varBtn6;
    private javax.swing.JButton varBtn7;
    private javax.swing.JButton varBtn8;
    private javax.swing.JButton varBtn9;
    private javax.swing.JButton varBtnClear;
    private javax.swing.JButton varBtnDot;
    private javax.swing.JTextField varChange;
    private javax.swing.JLabel varDate;
    private javax.swing.JTextField varDisplay;
    private javax.swing.JButton varExit;
    private javax.swing.JButton varPay;
    private javax.swing.JComboBox<String> varPayMethod;
    private javax.swing.JButton varPriceList;
    private javax.swing.JButton varPrint;
    private javax.swing.JButton varRemove;
    private javax.swing.JButton varReset;
    private javax.swing.JTextField varSubtotal;
    private javax.swing.JTextField varTax;
    private javax.swing.JLabel varTime;
    private javax.swing.JTextField varTotal;
    // End of variables declaration//GEN-END:variables
}
